### ISSUE TITLE
Fasta Inheritance Issue

### ISSUE THREAD

**Issue by brohammer** [LinkageIO/LocusPocus#1]
Assuming 'example.fa' exists in current directory. 

`from locuspocus import Fasta`
`x = Fasta.from_file('chr1', 'example.fa')`

Returns 

>   File "LocusPocus/locuspocus/Fasta.py", line 185, in from_file
>     self.add_chrom(cur_chrom,Chromosome("".join(cur_seqs)))
> TypeError: __init__() missing 1 required positional argument: 'seq'

**Comment by schae234** [comment]
Sorry @brohammer , I ran into this too. Ill push a fix and some extra tests.

Just curious, are you just playing around or are you planning on using this for something?

I've been dawdling on writing some actual docs for this, but I could definitely start here if someone else is using this.

**Comment by brohammer** [comment]
Thanks!

Mainly playing around right now, but I think it's useful. I'm particularly interested in using it for comparing nested TEs between individuals. The overlap and aggregate methods work well for this I think.

Everything in Locus is pretty straightforward just glancing through the code and the README is nice too. Would like to get a better handle on the Freezable class and how things are getting pushed/pulled to/from minus80 structures, which is why I was playing around with Fasta.

**Comment by brohammer** [comment]
Kept getting a 403 error when I tried to create a pull. 

The name argument here seems redundant. Should be ok to just add this line. 
```python
def add_chrom(self,chrom,cur=None):
   name = chrom.name
```
Then in `from_file`  change the two `add_chrom` lines to be like:
```python
self.add_chrom(Chromosome(cur_chrom, "".join(cur_seqs)),cur=cur)
```
This breaks `__repr__`, not sure of the purpose of this though. 

Works with the following test:

```
from Fasta import *
genome = Fasta("Rio")
Fasta.from_file(genome, 'example.fa')
```

**Comment by schae234** [comment]
Hey @brohammer,

I pushed all my changes to github and added tests to make sure that Fasta is working. You might need to also pull changes from Minus80. Ill work on adding docs and some examples next.

Not sure why youre getting a 403 error. Did you fork the repo and try opening a pull request? I don't see it on your profile.

**Comment by schae234** [comment]
Hey @brohammer 

Great to talk today. I'm going to close this issue unless you are still having problems. 

Let me know where you are with things, I'd love to have some more targeted use cases to show the utility of this code :+1:
