### ISSUE TITLE
LocusDist.pyx is not properly compiled during setup

### ISSUE THREAD

**Issue by SichongP** [LinkageIO/LocusPocus#7]
After running setup.py, no LocusDist.pyd file accompanying the pyx file. Trying to import any module in locuspocus resulted in error.
After manually importing pyximport; pyximport.install(), all modules can be successfully imported.

**Comment by schae234** [comment]
Hi @SichongP 

Super sorry about this. This repo is outdatad, please see the most current development at https://github.com/LinkageIO/LocusPocus 

If the bug still occurs on the above branch, I can definitely help out. To make sure this doesn't happen in the future, once you close this issue, I will delete this repository. Sorry about that!

**Comment by SichongP** [comment]
Thank you! It worked like charm!
